In [1]:
import numpy as np

In [2]:
a = np.array(['jay','af','asf'])

In [3]:
print(a)

['jay' 'af' 'asf']


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.arange(1,10)

In [6]:
print(b)

[1 2 3 4 5 6 7 8 9]


In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
c = np.zeros(3)

In [9]:
print(c)

[0. 0. 0.]


In [10]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
d = np.ones(3)

In [12]:
print(d)

[1. 1. 1.]


In [13]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
e = np.eye(3)

In [15]:
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
f = np.linspace(1,10,10)

In [17]:
print(f)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
print(np.linspace(1,100,4))

[  1.  34.  67. 100.]


In [19]:
g = np.shape(f)

In [20]:
print(g)

(10,)


In [21]:
h = f.reshape(2,5)

In [22]:
print(h)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [23]:
i = np.random.rand()
print(i)
i = np.random.rand(5)
print(i)
i = np.random.rand(3,2)
print(i)
# uniform distribution

0.3471507776669899
[0.27414336 0.91538256 0.54596807 0.81144409 0.27987613]
[[0.62478821 0.73049956]
 [0.31461878 0.48537693]
 [0.01755579 0.77290185]]


In [24]:
j = np.random.randint(10)
print(j)
j = np.random.randint(1,10)
print(j)
j = np.random.randint(1,10,2)
print(j)

1
2
[6 2]


In [25]:
k = np.random.randn(2)
print(k)
k = np.random.randn(4,3)
print(k)
# k = np.random.randn(1,5,2)
# print(k)3d
# standard normal distribution

[ 0.03695325 -2.42864025]
[[ 2.13979125 -0.89463329 -1.53499823]
 [ 0.08762547  0.63085498  0.82978446]
 [-1.27180955  1.03703073  1.65841919]
 [-0.04328079  1.12890351  0.22860933]]


In [26]:
m = np.max(f)

In [27]:
print(m)

10.0


In [28]:
n = np.min(f)

In [29]:
print(n)

1.0


In [30]:
o = np.mean(f)

In [31]:
print(o)

5.5


In [32]:
p = np.std(f)

In [33]:
print(p)

2.8722813232690143


In [34]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
q = np.arange(10).reshape(5,2).sum(axis=0)#col sum
r = np.arange(10).reshape(5,2).sum(axis=1)#row sum
print(q)
print(r)

[20 25]
[ 1  5  9 13 17]


In [36]:
arr = np.arange(10).reshape(5,2)

print(arr[2][1])
print(arr[2,1])

5
5


In [37]:
ar = np.arange(0,10)

In [38]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
ar[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
arr[::-1]#rev row

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [42]:
arr[::-1,::-1]#com rev

array([[9, 8],
       [7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

In [43]:
arr[:,::-1]#rev col

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

In [44]:
are = np.array([23,324,546,123,556])
print(np.sort(are))
print(are)
# np.sort(arr,axis,kind,order)

[ 23 123 324 546 556]
[ 23 324 546 123 556]


In [45]:
are[are>400]

array([546, 556])

In [46]:
a = np.array([[1,2],[4,5]])
b = np.array([[2,3],[0,1]])
print(np.matmul(a,b))
print(a.dot(b))
print(a@b)

[[ 2  5]
 [ 8 17]]
[[ 2  5]
 [ 8 17]]
[[ 2  5]
 [ 8 17]]


In [47]:
a

array([[1, 2],
       [4, 5]])

In [48]:
a + 10

array([[11, 12],
       [14, 15]])

In [49]:
a + a

array([[ 2,  4],
       [ 8, 10]])

In [50]:
import pandas as pd

In [51]:
s = pd.Series(np.arange(10,21))

In [52]:
# pd.Series(data,index,dtype,copy=False)

In [53]:
dates = pd.to_datetime('1st of july, 2023')

i = dates + pd.to_timedelta(np.arange(5),unit='D') 

d = [10,34,423,234,23]

time_series = pd.Series(data=d,index=i)

print(time_series)

print(pd.to_timedelta(np.arange(5),unit='D'))

2023-07-01     10
2023-07-02     34
2023-07-03    423
2023-07-04    234
2023-07-05     23
dtype: int64
TimedeltaIndex(['0 days', '1 days', '2 days', '3 days', '4 days'], dtype='timedelta64[ns]', freq=None)


In [54]:
# pd.Series(data,index,dtype,copy=False) #4

In [55]:
# pd.DataFrame(data,index,columns,dtype,copy=False) #5

In [56]:
d = {
    'ps':[10,20,30],
    'dm':[40,50,30]
}

df = pd.DataFrame(data=d,index=[1,2,3],columns=['ps','dm'])

In [57]:
df

ps  dm
1  10  40
2  20  50
3  30  30

In [58]:
df['ps']

1    10
2    20
3    30
Name: ps, dtype: int64

In [59]:
df[['ps','dm']]

ps  dm
1  10  40
2  20  50
3  30  30

In [60]:
df.loc[1]

ps    10
dm    40
Name: 1, dtype: int64

In [61]:
df.iloc[0]

ps    10
dm    40
Name: 1, dtype: int64

In [62]:
# df.drop(2,inplace=True)

In [63]:
df

ps  dm
1  10  40
2  20  50
3  30  30

In [64]:
df['total'] = df['ps']+df['dm']
df['total1'] = df['ps']+df['dm']

In [65]:
df

ps  dm  total  total1
1  10  40     50      50
2  20  50     70      70
3  30  30     60      60

In [66]:
df.drop('total1',axis=1,inplace=True)

In [67]:
df

ps  dm  total
1  10  40     50
2  20  50     70
3  30  30     60

In [68]:
df[df>30]

ps    dm  total
1 NaN  40.0     50
2 NaN  50.0     70
3 NaN   NaN     60

In [69]:
df.index.name = 'RollNo'

In [70]:
df

ps  dm  total
RollNo               
1       10  40     50
2       20  50     70
3       30  30     60

In [71]:
# df.reset_index()

In [72]:
df

ps  dm  total
RollNo               
1       10  40     50
2       20  50     70
3       30  30     60

In [73]:
dff = df[df>40]

In [74]:
dff

ps    dm  total
RollNo                 
1      NaN   NaN     50
2      NaN  50.0     70
3      NaN   NaN     60

In [75]:
dff.dropna(axis=0)

Empty DataFrame
Columns: [ps, dm, total]
Index: []

In [76]:
dff.dropna(axis=1)

total
RollNo       
1          50
2          70
3          60

In [77]:
dff

ps    dm  total
RollNo                 
1      NaN   NaN     50
2      NaN  50.0     70
3      NaN   NaN     60

In [78]:
dff.fillna(0)

ps    dm  total
RollNo                  
1       0.0   0.0     50
2       0.0  50.0     70
3       0.0   0.0     60

In [79]:
dff.interpolate(method='linear',axis=1)

ps    dm  total
RollNo                 
1      NaN   NaN   50.0
2      NaN  50.0   70.0
3      NaN   NaN   60.0